name: angular_youtube_player
description: Angular component for Youtube Iframe API
version: 0.1.1-alpha+2
homepage: https://lefty.io/
authors: 
  - Kevin Segaud <segaud.kevin@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.0.0
  youtube_iframe_interop: ^0.1.0

dev_dependencies:
  build_runner: ^1.6.0
  build_test: ^0.10.11
  build_web_compilers: ^2.1.0
  sass_builder: ^2.0.1
