name: angular_youtube_player
description: A sample command-line application.
version: 0.1.0
homepage: https://lefty.io/
authors: 
  - Kevin Segaud <segaud.kevin@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  dart_browser_loader: ^0.0.5
  js: 0.6.1+1

dev_dependencies:
  build: ^1.0.0
  build_runner: ^1.0.0
  build_test: '>=0.10.0 <1.0.0'
  build_web_compilers: '>=0.4.0 <1.0.0'
  sass_builder: ^2.0.1