name: angular_youtube_player
description: Angular component for Youtube Iframe API
version: 1.0.0
homepage: https://lefty.io/
repository: https://github.com/leftyio/angular_youtube_player
issue_tracker: https://github.com/leftyio/angular_youtube_player/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  youtube_iframe_interop: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.2.0
  sass_builder: ^2.1.0
  lints: ^1.0.0
